# Generated by Django 3.1.2 on 2021-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcitydetails',
            name='admin_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
