# Generated by Django 3.1.2 on 2021-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0002_destinationcitydetails_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcitydetails',
            name='city_rating',
            field=models.PositiveIntegerField(default='5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinationmetadetails',
            name='place_rating',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
