# Generated by Django 3.1.2 on 2021-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0003_auto_20210429_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=60)),
                ('place_ratings', models.PositiveIntegerField()),
            ],
        ),
    ]
