# Generated by Django 3.1.2 on 2021-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0004_placeratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeratings',
            name='user_info',
            field=models.CharField(default='syedarfa', max_length=25),
            preserve_default=False,
        ),
    ]
