# Generated by Django 3.1.2 on 2021-05-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0005_placeratings_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationcitydetails',
            name='destination_extras',
        ),
    ]
