# Generated by Django 3.1.2 on 2021-05-09 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureClub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristreview',
            name='adventureevent',
        ),
        migrations.RemoveField(
            model_name='touristreview',
            name='tourist_id',
        ),
        migrations.DeleteModel(
            name='EventDetails',
        ),
        migrations.DeleteModel(
            name='TouristReview',
        ),
    ]
